### PR TITLE
chore(localization): Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org/projects/lunasea/lunasea/)
for LunaSea/LunaSea.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by jagandeepbrar** [comment]
@all-contributors please add @almontegil for translation

**Comment by JagandeepBrar** [comment]
@all-contributors please add @TheSander562 for translation

**Comment by JagandeepBrar** [comment]
@all-contributors please add @Guilhermerrrr for translation

**Comment by JagandeepBrar** [comment]
@all-contributors please add @Ben-Wallner for translation

**Comment by JagandeepBrar** [comment]
@all-contributors please add @Sytom for translation

**Comment by JagandeepBrar** [comment]
@all-contributors please add @TheSander562 for translation

**Pull request merged**
