### PR TITLE
add docs for radarr, sonarr, tautulli

### PR DESCRIPTION
**Pull request by AliMickey**
i am unable to upload the images for some reason, here is the zip with all of them.

also i am unsure what configuration.md vs customization.md is for.

let me know of any errors.

[pr.zip](https://github.com/CometTools/LunaSea/files/6302491/pr.zip)

### CODE REVIEW

**Comment by jagandeepbrar** [comment]
Thanks for starting this! I will review and consider merging this in as I start to work on documentation closer to 5.0.0's release.

**Comment by jagandeepbrar** [comment]
> also i am unsure what configuration.md vs customization.md is for.

Also, sorry for not clarifying this, it was from the previous LunaSea releases which separated customization and configuration options for modules. Configuration would be the "Connection Details" section now, and customization would be any options like setting the termination message, etc.

**Comment by jagandeepbrar** [comment]
Hey @AliMickey, thanks for taking the time to originally do this, but instead I have typed out a bit more verbose instructions. I went with the assumption that anyone who needs to go with the docs needs a much more thorough explanation, and I also included some instructions for the web GUI side for some of them.

Not all modules are completed (but will be over the weekend), you can glance here how it differs: https://docs.lunasea.app/modules/sonarr

I will be closing this PR however, but I'll add you as a contributor to the docs to thank you for the effort that was taken to do these first steps 👍

**Comment by JagandeepBrar** [comment]
@all-contributors please add @AliMickey for documentation

**Comment by JagandeepBrar** [comment]
@all-contributors please add @AliMickey for docs

**Comment by AliMickey** [comment]
thanks, also can you add Turkish to the languages list on weblate. i can start translating.

**Comment by jagandeepbrar** [comment]
Hey @AliMickey, sorry for the long turnaround time (lots of things were going on for me for a bit) but I have added Turkish as a language on weblate! You can access the translation platform at https://www.lunasea.app/translate.

**Pull request closed without merging**
